[pytest]
markers =
    timeout: mark test to enforce a timeout limit
filterwarnings =
    ignore:pkg_resources is deprecated as an API.*:DeprecationWarning:pygame\.pkgdata
testpaths =
    tests
    src/zoo
addopts = -ra
